# Generated by Django 3.1.14 on 2023-02-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.CharField(default='ads', max_length=255, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
