# Generated by Django 3.1.14 on 2023-01-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_auto_20230122_1401'),
        ('certificates', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('client_info', models.CharField(max_length=255, verbose_name='Информация о клиенте')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('desired_completion_date', models.DateTimeField(verbose_name='Желаемая дата выполнения')),
                ('last_completion_date', models.DateTimeField(verbose_name='Желаемая дата выполнения')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificates', verbose_name='Сертификат')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
