# Generated by Django 3.1.14 on 2023-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20230122_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='last_completion_date',
            field=models.DateField(verbose_name='Последняя дата выполнения'),
        ),
    ]
