# Generated by Django 3.1.14 on 2023-01-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230122_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Обработан', 'PROCESSED'), ('Оплачен', 'PAID'), ('Откланен', 'REJECTED')], default='Откланен', max_length=100, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
