# Generated by Django 3.1.14 on 2023-01-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Обработан'), ('PAID', 'Оплачен'), ('REJECTED', 'Откланен')], max_length=100, verbose_name='Статус'),
        ),
    ]
