# Generated by Django 3.1.14 on 2023-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230125_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PENDING_PROCESSING', 'Ожидает обработки'), ('PROCESSED', 'Обработан'), ('PAID', 'Оплачен'), ('REJECTED', 'Отклонен')], default='PENDING_PROCESSING', max_length=100, verbose_name='Статус'),
        ),
    ]
