# Generated by Django 3.1.14 on 2023-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20230128_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.CharField(default='asd', max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
