# Generated by Django 3.1.14 on 2023-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='desired_completion_date',
            field=models.CharField(max_length=100, verbose_name='Желаемая дата выполнения'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='last_completion_date',
            field=models.CharField(max_length=100, verbose_name='Последняя дата выполнения'),
        ),
    ]
