# Generated by Django 3.1.14 on 2023-01-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20230130_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(blank=True, to='orders.OrderProducts', verbose_name='Товары'),
        ),
    ]
