# Generated by Django 3.1.14 on 2023-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20230131_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(default='asd', max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
