# Generated by Django 3.1.14 on 2023-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20230201_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая стоимость'),
        ),
    ]
