# Generated by Django 3.1.14 on 2023-03-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderproducts_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='bonus_coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бонусов'),
        ),
    ]
