# Generated by Django 3.1.14 on 2023-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='hash',
            field=models.CharField(max_length=255, unique=True, verbose_name='Хэш'),
        ),
    ]
