# Generated by Django 3.1.14 on 2023-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglists',
            name='sending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки'),
        ),
    ]
