# Generated by Django 3.1.14 on 2023-01-31 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Общая информация',
                'verbose_name_plural': 'Общая информация',
            },
        ),
        migrations.CreateModel(
            name='StoreInfoVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='ID файла в телеграмме')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_info.storeinfo', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Видеоролик',
                'verbose_name_plural': 'Видеоролики',
            },
        ),
        migrations.CreateModel(
            name='StoreInfoImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, verbose_name='ID файла в телеграмме')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_info.storeinfo', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
