# Generated by Django 3.1.14 on 2023-01-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='Категория'),
        ),
    ]
