# Generated by Django 3.1.14 on 2023-01-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230128_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='additional_products',
            field=models.ManyToManyField(blank=True, null=True, to='products.AdditionalProducts', verbose_name='Дополнительные опции'),
        ),
    ]
