# Generated by Django 3.1.14 on 2023-01-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230128_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='photo',
            new_name='telegram_id',
        ),
    ]
