# Generated by Django 3.1.14 on 2023-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230209_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='preview_url',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью для инлайн поиска'),
        ),
    ]
