# Generated by Django 3.1.14 on 2023-01-24 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketproducts',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AddField(
            model_name='basketproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
    ]
