# Generated by Django 3.1.14 on 2023-01-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230128_1436'),
        ('basket', '0002_auto_20230124_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproducts',
            name='additional_products',
            field=models.ManyToManyField(blank=True, to='products.AdditionalProducts', verbose_name='Дополнительные товары'),
        ),
    ]
