# Generated by Django 3.1.14 on 2023-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телеграмм username'),
        ),
    ]
