# Generated by Django 3.1.14 on 2023-01-31 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20230122_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='coins',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Монеты'),
        ),
        migrations.AddField(
            model_name='clients',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clients', verbose_name='Реферрер'),
        ),
    ]
