# Generated by Django 3.1.14 on 2023-01-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20230131_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='orders_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов'),
        ),
    ]
